using CrossSolar.Domain;
using System.Collections.Generic;
using System.Threading.Tasks;
using CrossSolar.Models;

namespace CrossSolar.Repository
{   
    public interface IDayAnalyticsRepository : IGenericRepository<OneDayElectricityModel>
    {
        //added
        //display panel’s all historical data in a chart, in which each
        //point represents electricity generated by this panel each 
        //day[sum, min, max, average]
        //up to the end
        //    List<OneDayElectricityModel> GetHistory(int panelId);
        Task<List<OneDayElectricityModel>> GetHistory(int panelId);
        //Task<IEnumerable<OneDayElectricityModel>> GetHistory(int panelId);
    }
}